export const allImages = [
  {
    id: 1,
    categroy: "interior",
    images: [
      "interior/1.jpg",
      "interior/2.jpg",
      "interior/3.jpg",
      "interior/4.jpg",
      "interior/5.jpeg",
    ],
    name: "Interior",
    url: "gallery/interior",
    image: "/interior/2.jpg",
  },
  {
    id: 2,
    categroy: "exterior",
    images: [
      "exterior/1.jpg",
      "exterior/2.jpg",
      "exterior/3.png",
      "exterior/4.jpg",
    ],
    name: "Exterior",
    url: "gallery/exterior",
    image: "/exterior/4.jpg",
  },
  {
    id: 3,
    categroy: "event",
    images: [
      "event/1.jpeg",
      "event/2.png",
      "event/3.png",
      "event/4.png",
      "event/5.jpeg",
      "event/6.png",
      "event/7.jpeg",
      "event/8.jpeg",
      "event/9.png",
    ],
    name: "Events",
    url: "gallery/event",
    image: "/event/7.jpeg",
  },
  {
    id: 4,
    categroy: "launch_photos",
    images: [
      "launch_photos/1.jpg",
      "launch_photos/2.jpg",
      "launch_photos/3.jpg",
      "launch_photos/4.jpg",
      "launch_photos/5.jpg",
      "launch_photos/6.jpg",
      "launch_photos/7.jpg",
      "launch_photos/8.jpg",
      "launch_photos/9.jpg",
      "launch_photos/10.jpg",
      "launch_photos/11.jpg",
      "launch_photos/12.jpg",
    ],
    name: "Launch Day",
    url: "gallery/launch_photos",
    image: "/launch_photos/8.jpg",
  },
  {
    id: 5,
    categroy: "Modalities",
    images: [
      "instruments/1.jpg",
      "instruments/2.jpg",
      "instruments/3.jpg",
      "instruments/4.jpg",
      "instruments/5.jpg",
      "instruments/6.jpg",
      "instruments/7.jpg",
      "instruments/8.1.png",
      "instruments/9.1.png",
    ],
    name: "Modalities",
    url: "gallery/Modalities",
    image: "/instruments/1.jpg",
  },
  {
    id: 6,
    categroy: "our-team",
    images: [
      "our-team/1.jpg",
      "our-team/2.jpg",
      "our-team/3.jpg",
      "our-team/4.jpg",
      "our-team/5.jpg",
      "our-team/6.jpg",
      "our-team/7.jpg",
    ],
    name: "Our Team",
    url: "gallery/our-team",
    image: "/our-team/1.jpg",
  },
  {
    id: 7,
    categroy: "all",
    name: "All",
    url: "gallery/all",
    image: "/interior/1.jpg",
    images: [
      "our-team/1.jpg",
      "our-team/2.jpg",
      "our-team/3.jpg",
      "our-team/4.jpg",
      "our-team/5.jpg",
      "our-team/6.jpg",
      "our-team/7.jpg",
      "instruments/1.jpg",
      "instruments/2.jpg",
      "instruments/3.jpg",
      "instruments/4.jpg",
      "instruments/5.jpg",
      "instruments/6.jpg",
      "instruments/7.jpg",
      "instruments/8.1.png",
      "instruments/9.1.png",
      "launch_photos/1.jpg",
      "launch_photos/2.jpg",
      "launch_photos/3.jpg",
      "launch_photos/4.jpg",
      "launch_photos/5.jpg",
      "launch_photos/6.jpg",
      "launch_photos/7.jpg",
      "launch_photos/8.jpg",
      "launch_photos/9.jpg",
      "launch_photos/10.jpg",
      "launch_photos/11.jpg",
      "launch_photos/12.jpg",
      "event/1.jpeg",
      "event/2.png",
      "event/3.png",
      "event/4.png",
      "event/5.jpeg",
      "event/6.png",
      "event/7.jpeg",
      "event/8.jpeg",
      "event/9.png",
      "exterior/1.jpg",
      "exterior/2.jpg",
      "exterior/3.png",
      "exterior/4.jpg",
      "interior/1.jpg",
      "interior/2.jpg",
      "interior/3.jpg",
      "interior/4.jpg",
      "interior/5.jpeg",
    ],
  },
  {
    id: 8,
    categroy: "videos",
    name: "Videos",
    url: "gallery/videos",
    image: "/interior/1.jpg",
    images: [],
  },
];
