export const service = [
  {
    id: 1,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED FNAC INCLUDING SMEAR EXAMINATION ",
    url: "/",
    price: "6000",
  },
  {
    id: 2,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED LIVER BIOPSY INCLUDING HPE ",
    url: "/",
    price: "13000",
  },
  {
    id: 3,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED ASPIRATION ",
    url: "/",
    price: "4000",
  },
  {
    id: 4,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED ABSCESS DRAINAGE ",
    url: "/",
    price: "6000",
  },
  {
    id: 5,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED CATHETER DRAINAGE (WITHOUT MATERIAL) ",
    url: "/",
    price: "7000",
  },
  {
    id: 6,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED STEROID INJECTION ",
    url: "/",
    price: "4500",
  },
  {
    id: 7,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED BREAST MARKER CLIP (EXCLUDING MATERIAL) ",
    url: "/",
    price: "4000",
  },
  {
    id: 8,
    category: "INTERVENTION RADIOLOGY",
    name: "ULTRASOUND GUIDED J WIRE INSERTION (EXCLUDING MATERIAL) ",
    url: "/",
    price: "4000",
  },
  {
    id: 9,
    category: "ECHO",
    name: "COLOR DOPPLER SINGLE LIMB ARTERIAL / VENOUS ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 10,
    category: "ECHO",
    name: "COLOR DOPPLER BOTH LIMBS ARTERIAL / VENOUS ",
    url: "/services/2d-echo",
    price: "6000",
  },
  {
    id: 11,
    category: "ECHO",
    name: "CAROTID COLOR DOPPLER ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 12,
    category: "ECHO",
    name: "RENAL ARTERY DOPPLER ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 13,
    category: "ECHO",
    name: "ECG ",
    url: "/services/2d-echo",
    price: "400",
  },
  {
    id: 14,
    category: "ECHO",
    name: "HOLTER MONITORING ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 15,
    category: "ECHO",
    name: "TMT ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 16,
    category: "ECHO",
    name: "2D ECHO ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 17,
    category: "ECHO",
    name: "FETAL ECHO",
    url: "/services/2d-echo",
    price: "4000",
  },
  {
    id: 18,
    category: "ECHO",
    name: "PEDIATRIC ECHO ",
    url: "/services/2d-echo",
    price: "3500",
  },
  {
    id: 19,
    category: "ECHO",
    name: "STRESS ECHO ",
    url: "/services/2d-echo",
    price: "4500",
  },
  {
    id: 20,
    category: "ECHO",
    name: "DOBUTAMINE STRESS ECHO ",
    url: "/services/2d-echo",
    price: "5000",
  },
  {
    id: 21,
    category: "ECHO",
    name: "ABPM (Ambulatory Blood Pressure Monitoring) ",
    url: "/services/2d-echo",
    price: "2500",
  },
  {
    id: 22,
    category: "ECHO",
    name: "PFT ",
    url: "/services/2d-echo",
    price: "2200",
  },
  {
    id: 23,
    category: "ECHO",
    name: "UROFLOMETRY ",
    url: "/services/2d-echo",
    price: "1500",
  },
  {
    id: 24,
    category: "ECHO",
    name: "EEG ",
    url: "/services/2d-echo",
    price: "3000",
  },
  {
    id: 25,
    category: "ECHO",
    name: "NCV SINGLE LIMB ",
    url: "/services/2d-echo",
    price: "2000",
  },
  {
    id: 26,
    category: "ECHO",
    name: "EMG SINGLE LIMB ",
    url: "/services/2d-echo",
    price: "2000",
  },
  {
    id: 27,
    category: "ULTRASOUND",
    name: "ULTRASOUND LOWER ABDOMEN ",
    url: "/services/ultrasound",
    price: "1500",
  },
  {
    id: 28,
    category: "ULTRASOUND",
    name: "ULTRASOUND LOWER ABDOMEN TVS ",
    url: "/services/ultrasound",
    price: "1600",
  },
  {
    id: 29,
    category: "ULTRASOUND",
    name: "ULTRASOUND LOWER ABDOMEN + 3D ",
    url: "/services/ultrasound",
    price: "2800",
  },
  {
    id: 30,
    category: "ULTRASOUND",
    name: "ULTRASOUND UPPER ABDOMEN ",
    url: "/services/ultrasound",
    price: "1500",
  },
  {
    id: 31,
    category: "ULTRASOUND",
    name: "ULTRASOUND WHOLE ABDOMEN + TVS ",
    url: "/services/ultrasound",
    price: "2300",
  },
  {
    id: 32,
    category: "ULTRASOUND",
    name: "ULTRASOUND WHOLE ABDOMEN ",
    url: "/services/ultrasound",
    price: "1800",
  },
  {
    id: 33,
    category: "ULTRASOUND",
    name: "ULTRASOUND KUB ",
    url: "/services/ultrasound",
    price: "1500",
  },
  {
    id: 34,
    category: "ULTRASOUND",
    name: "ULTRASOUND KUB + PVR ",
    url: "/services/ultrasound",
    price: "1800",
  },
  {
    id: 35,
    category: "ULTRASOUND",
    name: "ULTRASOUND FOLLICULAR (UPTO 5 VISITS) ",
    url: "/services/ultrasound",
    price: "3500",
  },
  {
    id: 36,
    category: "ULTRASOUND",
    name: "ULTRASOUND FOLLICULAR SINGLE SCAN ",
    url: "/services/ultrasound",
    price: "1000",
  },
  {
    id: 37,
    category: "ULTRASOUND",
    name: "ULTRASOUND FOR CHEST ",
    url: "/services/ultrasound",
    price: "1800",
  },
  {
    id: 38,
    category: "ULTRASOUND",
    name: "ULTRASOUND UPPER AB & CHEST ",
    url: "/services/ultrasound",
    price: "3200",
  },
  {
    id: 39,
    category: "ULTRASOUND",
    name: "ULTRASOUND TESTES/SCROTUM ",
    url: "/services/ultrasound",
    price: "3000",
  },
  {
    id: 40,
    category: "ULTRASOUND",
    name: "ULTRASOUND B SCAN ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 41,
    category: "ULTRASOUND",
    name: "TRUS FOR PROSTATE ",
    url: "/services/ultrasound",
    price: "3000",
  },
  {
    id: 42,
    category: "ULTRASOUND",
    name: "ULTRASOUND SINGLE BREAST ",
    url: "/services/ultrasound",
    price: "1500",
  },
  {
    id: 43,
    category: "ULTRASOUND",
    name: "ULTRASOUND BOTH BREAST ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 44,
    category: "ULTRASOUND",
    name: "ULTRASOUND SHOULDER ",
    url: "/services/ultrasound",
    price: "3000",
  },
  {
    id: 45,
    category: "ULTRASOUND",
    name: "ULTRASOUND SMALL PART ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 46,
    category: "ULTRASOUND",
    name: "ULTRASOUND NT & NB SCAN ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 47,
    category: "ULTRASOUND",
    name: "ULTRASOUND LEVEL II ",
    url: "/services/ultrasound",
    price: "3500",
  },
  {
    id: 48,
    category: "ULTRASOUND",
    name: "ULTRASOUND OBS ",
    url: "/services/ultrasound",
    price: "2000",
  },
  {
    id: 49,
    category: "ULTRASOUND",
    name: "ULTRASOUND OBS+BPS ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 50,
    category: "ULTRASOUND",
    name: "ULTRASOUND OBS WITH COLOR DOPPLER ",
    url: "/services/ultrasound",
    price: "2500",
  },
  {
    id: 51,
    category: "ULTRASOUND",
    name: "ULTRASOUND OBS + BPS +COLOR DOPPLER ",
    url: "/services/ultrasound",
    price: "3500",
  },
  {
    id: 52,
    category: "ULTRASOUND",
    name: "4D IMAGE ",
    url: "/services/ultrasound",
    price: "1100",
  },
  {
    id: 53,
    category: "ULTRASOUND",
    name: "ULTRASOUND FETAL ECHO ",
    url: "/services/ultrasound",
    price: "4000",
  },
  {
    id: 54,
    category: "Hematology",
    name: "CBC ",
    url: "/",
    price: "350",
  },
  {
    id: 55,
    category: "Hematology",
    name: "HEAMOGRAM ",
    url: "/",
    price: "500",
  },
  {
    id: 56,
    category: "Hematology",
    name: "HEAMOGLOBIN(HB) ",
    url: "/",
    price: "150",
  },
  {
    id: 57,
    category: "Hematology",
    name: "TLC ",
    url: "/",
    price: "110",
  },
  {
    id: 58,
    category: "Hematology",
    name: "DLC ",
    url: "/",
    price: "130",
  },
  {
    id: 59,
    category: "Hematology",
    url: "/",
    name: "ESR ",
    price: "110",
  },
  {
    id: 60,
    category: "Hematology",
    url: "/",
    name: "RBC COUNT ",
    price: "120",
  },
  {
    id: 61,
    category: "Hematology",
    name: "AEC ",
    url: "/",
    price: "150",
  },
  {
    id: 62,
    category: "Hematology",
    name: "RETICLOCYTE COUNT ",
    url: "/",
    price: "250",
  },
  {
    id: 63,
    category: "Hematology",
    name: "PLATELET COUNT ",
    url: "/",
    price: "150",
  },
  {
    id: 64,
    category: "Hematology",
    name: "PCV ",
    url: "/",
    price: "150",
  },
  {
    id: 65,
    category: "Hematology",
    name: "PERIPHERAL SMEAR (P.S.) ",
    price: "250",
    url: "/",
  },
  {
    id: 66,
    category: "Hematology",
    name: "M.P. ",
    url: "/",
    price: "150",
  },
  {
    id: 67,
    category: "Hematology",
    name: "MICROFILARIA ",
    url: "/",
    price: "400",
  },
  {
    id: 68,
    category: "Hematology",
    name: "BLOOD GROUP ABO & RH TYPING ",
    url: "/",
    price: "150",
  },
  {
    id: 69,
    category: "Hematology",
    url: "/",
    name: "BT ",
    price: "200",
  },
  {
    id: 70,
    category: "Hematology",
    name: "L.E. CELL PHENOMENON ",
    url: "/",
    price: "500",
  },
  {
    id: 71,
    category: "Hematology",
    name: "BONE MARROW REPORTING ",
    url: "/",
    price: "7500",
  },
  {
    id: 72,
    category: "Hematology",
    url: "/",
    name: "G6 PD ",
    price: "700",
  },
  {
    id: 73,
    category: "Hematology",
    name: "CLOT RETRACTION TEST ",
    url: "/",
    price: "200",
  },
  {
    id: 74,
    category: "Hematology",
    name: "PROTHROMBIN TIME(PT/INR) ",
    url: "/",
    price: "300",
  },
  {
    id: 75,
    category: "Hematology",
    url: "/",
    name: "PTT(APTT) ",
    price: "400",
  },
  {
    id: 76,
    category: "Hematology",
    name: "COOMB'S TEST DIRECT ",
    url: "/",
    price: "500",
  },
  {
    id: 77,
    category: "Hematology",
    url: "/",
    name: "SERUM IRON ",
    price: "350",
  },
  {
    id: 78,
    category: "Hematology",
    name: "SERUM FERRITIN ",
    url: "/",
    price: "600",
  },
  {
    id: 79,
    category: "Hematology",
    name: "RAPID MALARIA TEST ",
    url: "/",
    price: "550",
  },
  {
    id: 80,
    category: "Hematology",
    url: "/",
    name: "HBA1C ",
    price: "450",
  },
  {
    id: 81,
    category: "Hematology",
    name: "COOMB'S TEST INDIRECT ",
    url: "/",
    price: "600",
  },
  {
    id: 82,
    category: "Hematology",
    url: "/",
    name: "COOMB'S TEST GEL ",
    price: "700",
  },
  {
    id: 83,
    category: "Hematology",
    url: "/",
    name: "TIBC ",
    price: "350",
  },
  {
    id: 84,
    category: "Hematology",
    url: "/",
    name: "CT ",
    price: "200",
  },
  {
    id: 85,
    category: "Biochemistry",
    name: "BLOOD SUGAR FASTING ",
    url: "/",
    price: "110",
  },
  {
    id: 86,
    category: "Biochemistry",
    name: "BLOOD SUGAR PP ",
    url: "/",
    price: "110",
  },
  {
    id: 87,
    category: "Biochemistry",
    name: "BLOOD SUGAR RANDOM ",
    url: "/",
    price: "110",
  },
  {
    id: 88,
    category: "Biochemistry",
    name: "BLOOD SUGAR F/PP ",
    url: "/",
    price: "200",
  },
  {
    id: 89,
    category: "Biochemistry",
    name: "LIPID PROFILE ",
    url: "/",
    price: "850",
  },
  {
    id: 90,
    category: "Biochemistry",
    name: "LIVER FUNCTION TEST ",
    url: "/",
    price: "700",
  },
  {
    id: 91,
    category: "Biochemistry",
    name: "KIDNEY FUNCTION TEST ",
    url: "/",
    price: "800",
  },
  {
    id: 92,
    category: "Biochemistry",
    name: "SERUM TRIGYLICERIDES ",
    url: "/",
    price: "250",
  },
  {
    id: 93,
    category: "Biochemistry",
    name: "SERUM CHOLESTROL ",
    url: "/",
    price: "150",
  },
  {
    id: 94,
    category: "Biochemistry",
    name: "HDL CHOLESTROL ",
    price: "300",
    url: "/",
  },
  {
    id: 95,
    category: "Biochemistry",
    url: "/",
    name: "VLDL CHOLESTROL ",
    price: "300",
  },
  {
    id: 96,
    category: "Biochemistry",
    url: "/",
    name: "BLOOD UREA ",
    price: "130",
  },
  {
    id: 97,
    category: "Biochemistry",
    name: "SERUM CREATININE ",
    url: "/",
    price: "130",
  },
  {
    id: 98,
    category: "Biochemistry",
    url: "/",
    name: "SERUM URIC ACID ",
    price: "130",
  },
  {
    id: 99,
    category: "Biochemistry",
    name: "SERUM CALCIUM ",
    url: "/",
    price: "150",
  },
  {
    id: 100,
    category: "Biochemistry",
    name: "SERUM PHOSPHORUS ",
    url: "/",
    price: "150",
  },
  {
    id: 101,
    category: "Biochemistry",
    name: "SERUM BILIRUBIN ",
    url: "/",
    price: "250",
  },
  {
    id: 102,
    category: "Biochemistry",
    url: "/",
    name: "SERUM SGOT ",
    price: "150",
  },
  {
    id: 103,
    category: "Biochemistry",
    name: "SERUM SGPT ",
    url: "/",
    price: "150",
  },
  {
    id: 104,
    category: "Biochemistry",
    name: "SERUM ALKALINE PHOSPHATASE ",
    url: "/",
    price: "150",
  },
  {
    id: 105,
    category: "Biochemistry",
    name: "SERUM PROTEIN ",
    price: "200",
    url: "/",
  },
  {
    id: 106,
    category: "Biochemistry",
    url: "/",
    name: "SERUM ELECTROLYTES ",
    price: "450",
  },
  {
    id: 107,
    category: "Biochemistry",
    url: "/",
    name: "SERUM AMYLASE ",
    price: "400",
  },
  {
    id: 108,
    category: "Biochemistry",
    name: "SERUM LIPASE ",
    url: "/",
    price: "600",
  },
  {
    id: 109,
    category: "Biochemistry",
    name: "CPK ",
    url: "/",
    price: "300",
  },
  {
    id: 110,
    category: "Biochemistry",
    name: "CPK MB ",
    url: "/",
    price: "400",
  },
  {
    id: 111,
    category: "Biochemistry",
    name: "LDH ",
    url: "/",
    price: "400",
  },
  {
    id: 112,
    category: "Biochemistry",
    name: "SERUM CHLORIDE ",
    url: "/",
    price: "150",
  },
  {
    id: 113,
    category: "Biochemistry",
    name: "GAMMA G.T. ",
    url: "/",
    price: "300",
  },
  {
    id: 114,
    category: "SEROLOGY",
    name: "R.A. FACTOR (QUANTITATIVE) ",
    url: "/",
    price: "400",
  },
  {
    id: 115,
    category: "SEROLOGY",
    url: "/",
    name: "WIDAL TEST ",
    price: "250",
  },
  {
    id: 116,
    category: "SEROLOGY",
    url: "/",
    name: "V.D.R.L. (SYPHISTIX) ",
    price: "170",
  },
  {
    id: 117,
    category: "SEROLOGY",
    url: "/",
    name: "R.A. FACTOR ",
    price: "150",
  },
  {
    id: 118,
    category: "SEROLOGY",
    name: "C.R.P. ",
    url: "/",
    price: "250",
  },
  {
    id: 119,
    category: "SEROLOGY",
    name: "HBSag ",
    price: "500",
    url: "/",
  },
  {
    id: 120,
    category: "SEROLOGY",
    url: "/",
    name: "ANA ",
    price: "700",
  },
  {
    id: 121,
    category: "SEROLOGY",
    name: "HEPATITIS C ",
    url: "/",
    price: "600",
  },
  {
    id: 122,
    category: "SEROLOGY",
    name: "TYPHIDOT IGG/IGM ",
    url: "/",
    price: "650",
  },
  {
    id: 123,
    category: "SEROLOGY",
    url: "/",
    name: "HIV I & II ",
    price: "600",
  },
  {
    id: 124,
    category: "SEROLOGY",
    name: "DENGUE SEROLOGY IGM/IGG ",
    url: "/",
    price: "1800",
  },
  {
    id: 125,
    category: "SEROLOGY",
    name: "DENGUE PROFILE ",
    url: "/",
    price: "2500",
  },
  {
    id: 126,
    category: "SEROLOGY",
    url: "/",
    name: "NS1 ANTIGEN ",
    price: "1800",
  },
  {
    id: 127,
    category: "SEROLOGY",
    url: "/",
    name: "C.R.P. (QUANTITATIVE) ",
    price: "400",
  },
  {
    id: 128,
    category: "SEROLOGY",
    name: "ANF ",
    url: "/",
    price: "700",
  },
  {
    id: 129,
    category: "URINE",
    name: "URINE ROUTINE & MICROSCOPY (R/M) ",
    url: "/",
    price: "110",
  },
  {
    id: 130,
    category: "URINE",
    name: "UROBILINOGEN ",
    url: "/",
    price: "110",
  },
  {
    id: 131,
    category: "URINE",
    name: "BILE PIGMENT ",
    url: "/",
    price: "120",
  },
  {
    id: 132,
    category: "URINE",
    name: "KETONE BODIES (ACETONE) ",
    url: "/",
    price: "1700",
  },
  {
    id: 133,
    category: "URINE",
    name: "BENCE JONE'S PROTEIN ",
    url: "/",
    price: "500",
  },
  {
    id: 134,
    category: "URINE",
    name: "URINE PREGNANCY TEST ",
    url: "/",
    price: "150",
  },
  {
    id: 135,
    category: "URINE",
    name: "URINE CULTURE & SENSITIVITY ",
    url: "/",
    price: "700",
  },
  {
    id: 136,
    category: "URINE",
    name: "URINE PROTEINS (24 HOURS) ",
    url: "/",
    price: "200",
  },
  {
    id: 137,
    category: "URINE",
    name: "URINARY CALCIUM (24 HOURS) ",
    url: "/",
    price: "200",
  },
  {
    id: 138,
    category: "URINE",
    url: "/",
    name: "URINARY CREATININE (24 HOURS) ",
    price: "200",
  },
  {
    id: 139,
    category: "URINE",
    name: "URINARY URIC ACID (24 HOURS) ",
    url: "/",
    price: "200",
  },
  {
    id: 140,
    category: "URINE",
    name: "CREATININE CLEARANCE ",
    url: "/",
    price: "500",
  },
  {
    id: 141,
    category: "URINE",
    name: "MICROALBUMIN ",
    url: "/",
    price: "500",
  },
  {
    id: 142,
    category: "URINE",
    name: "BILE SALT ",
    url: "/",
    price: "120",
  },
  {
    id: 143,
    category: "STOOL",
    name: "STOOL ROUTINE & MICROSCOPY (R/M) ",
    url: "/",
    price: "120",
  },
  {
    id: 144,
    category: "STOOL",
    name: "OCCULT BLOOD ",
    url: "/",
    price: "200",
  },
  {
    id: 145,
    category: "STOOL",
    name: "STOOL CULTURE & SENSITIVITY ",
    url: "/",
    price: "700",
  },
  {
    id: 146,
    category: "STOOL",
    name: "REDUCING SUGAR & PH ",
    url: "/",
    price: "120",
  },
  {
    id: 147,
    category: "SEMEN",
    name: "SEMEN ANALYSIS ROUTINE ",
    url: "/",
    price: "400",
  },
  {
    id: 148,
    category: "SEMEN",
    name: "SEMEN CULTURE & SENSITIVITY ",
    url: "/",
    price: "700",
  },
  {
    id: 149,
    category: "MICROBIOLOGY ",
    name: "GRAM'S STAIN ",
    url: "/",
    price: "300",
  },
  {
    id: 150,
    category: "MICROBIOLOGY ",
    url: "/",
    name: "A.F.B. STAIN ",
    price: "300",
  },
  {
    id: 151,
    category: "MICROBIOLOGY ",
    name: "VAGINAL SWAB FOR MONILIA TRICHOMONAS ",
    url: "/",
    price: "700",
  },
  {
    id: 152,
    category: "MICROBIOLOGY ",
    name: "ALBERT STAIN (DIPHTHERIA) ",
    url: "/",
    price: "350",
  },
  {
    id: 153,
    category: "MICROBIOLOGY ",
    url: "/",
    name: "URETHRAL SWAB ",
    price: "350",
  },
  {
    id: 154,
    category: "MICROBIOLOGY ",
    name: "CULTURE & SENSITIVITY PUS, STOOL, URINE ",
    url: "/",
    price: "700",
  },
  {
    id: 155,
    category: "MICROBIOLOGY ",
    name: "FUNGAL SMEAR (KOH) ",
    url: "/",
    price: "300",
  },
  {
    id: 156,
    category: "MICROBIOLOGY ",
    name: "BLOOD CULTURE ",
    url: "/",
    price: "1000",
  },
  {
    id: 157,
    category: "MICROBIOLOGY ",
    name: "RAPID BLOOD CULTURE ",
    url: "/",
    price: "1000",
  },
  {
    id: 158,
    category: "MICROBIOLOGY ",
    name: "A.F.B. CULTURE ",
    url: "/",
    price: "1000",
  },
  {
    id: 159,
    category: "HORMONES",
    name: "T3 ",
    url: "/",
    price: "250",
  },
  {
    id: 160,
    category: "HORMONES",
    name: "T4 ",
    price: "250",
    url: "/",
  },
  {
    id: 161,
    category: "HORMONES",
    url: "/",
    name: "TSH ",
    price: "300",
  },
  {
    id: 162,
    category: "HORMONES",
    url: "/",
    name: "FT3 ",
    price: "300",
  },
  {
    id: 163,
    category: "HORMONES",
    url: "/",
    name: "FT4 ",
    price: "300",
  },
  {
    id: 164,
    category: "HORMONES",
    name: "THYROID TEST ",
    url: "/",
    price: "750",
  },
  {
    id: 165,
    category: "HORMONES",
    name: "FREE THYROID TEST ",
    url: "/",
    price: "800",
  },
  {
    id: 166,
    category: "HORMONES",
    name: "LH ",
    url: "/",
    price: "500",
  },
  {
    id: 167,
    category: "HORMONES",
    name: "FSH ",
    url: "/",
    price: "500",
  },
  {
    id: 168,
    category: "HORMONES",
    name: "PROLACTIN ",
    url: "/",
    price: "500",
  },
  {
    id: 169,
    category: "HORMONES",
    url: "/",
    name: "TOXO ",
    price: "550",
  },
  {
    id: 170,
    category: "HORMONES",
    url: "/",
    name: "RUBELLA ",
    price: "550",
  },
  {
    id: 171,
    category: "HORMONES",
    name: "CYTOMEGALO ",
    url: "/",
    price: "550",
  },
  {
    id: 172,
    category: "HORMONES",
    name: "HERPES ",
    url: "/",
    price: "800",
  },
  {
    id: 173,
    category: "HORMONES",
    name: "TORCH IGG/IGM/IGA EACH ",
    url: "/",
    price: "2000",
  },
  {
    id: 174,
    category: "HORMONES",
    name: "PROGESTERONES ",
    url: "/",
    price: "600",
  },
  {
    id: 175,
    category: "HORMONES",
    url: "/",
    name: "ESTRADIOL ",
    price: "600",
  },
  {
    id: 176,
    category: "HORMONES",
    name: "TESTOSTERONE ",
    url: "/",
    price: "600",
  },
  {
    id: 177,
    category: "HORMONES",
    name: "FREE TESTOSTERONE ",
    url: "/",
    price: "1800",
  },
  {
    id: 178,
    category: "HORMONES",
    name: "ANTI MULERIAN HORMONES ",
    url: "/",
    price: "1800",
  },
  {
    id: 179,
    category: "HORMONES",
    url: "/",
    name: "INSULIN FASTING ",
    price: "700",
  },
  {
    id: 180,
    category: "HORMONES",
    url: "/",
    name: "INSULIN PP ",
    price: "700",
  },
  {
    id: 181,
    category: "HORMONES",
    name: "INSULIN RANDOM ",
    url: "/",
    price: "700",
  },
  {
    id: 182,
    category: "HORMONES",
    name: "PARA THYROID HORMONES ",
    url: "/",
    price: "1450",
  },
  {
    id: 183,
    category: "HORMONES",
    name: "CORTISOL MORNING/EVENING EACH ",
    price: "500",
    url: "/",
  },
  {
    id: 184,
    url: "/",
    category: "HORMONES",
    name: "DHEAS ",
    price: "900",
  },
  {
    id: 185,
    category: "MISCELLANEOUS EXAMINATION",
    url: "/",
    name: "MONTOUX ",
    price: "200",
  },
  {
    id: 186,
    category: "SPECIAL TEST ",
    url: "/",
    name: "HPLC ",
    price: "900",
  },
  {
    id: 187,
    category: "SPECIAL TEST ",
    url: "/",
    name: "VITAMIN B12 ",
    price: "1000",
  },
  {
    id: 188,
    category: "SPECIAL TEST ",
    url: "/",
    name: "FOLIC ACID ",
    price: "1100",
  },
  {
    id: 189,
    category: "SPECIAL TEST ",
    url: "/",
    name: "VITAMIN D3 ",
    price: "1570",
  },
  {
    id: 190,
    category: "SPECIAL TEST ",
    name: "MICRO ALBUMIN: CREATININE RATIO ",
    url: "/",
    price: "600",
  },
  {
    id: 191,
    category: "SPECIAL TEST ",
    url: "/",
    name: "ADA ",
    price: "550",
  },
  {
    id: 192,
    category: "SPECIAL TEST ",
    name: "PCR MYCOBACTERIA ",
    url: "/",
    price: "1800",
  },
  {
    id: 193,
    category: "SPECIAL TEST ",
    url: "/",
    name: "GENE EXPERT ",
    price: "3500",
  },
  {
    id: 194,
    category: "SPECIAL TEST ",
    name: "QUANTIFERON TB GOLD ",
    price: "2800",
    url: "/",
  },
  {
    id: 195,
    category: "SPECIAL TEST ",
    url: "/",
    name: "ANTI CCP ",
    price: "1650",
  },
  {
    id: 196,
    category: "SPECIAL TEST ",
    url: "/",
    name: "IgE LEVEL ",
    price: "750",
  },
  {
    id: 197,
    category: "SPECIAL TEST ",
    url: "/",
    name: "DOUBLE MARKER ",
    price: "2500",
  },
  {
    id: 198,
    category: "SPECIAL TEST ",
    name: "TRIPLE MARKER ",
    url: "/",
    price: "2800",
  },
  {
    id: 199,
    category: "SPECIAL TEST ",
    url: "/",
    name: "QUADRIPLE MARKER ",
    price: "3600",
  },
  {
    id: 200,
    category: "SPECIAL TEST ",
    name: "HCG LEVEL ",
    url: "/",
    price: "350",
  },
  {
    id: 201,
    category: "SPECIAL TEST ",
    name: "PSA (TOTAL) ",
    url: "/",
    price: "700",
  },
  {
    id: 202,
    category: "SPECIAL TEST ",
    url: "/",
    name: "PSA (FREE) ",
    price: "750",
  },
  {
    id: 203,
    category: "SPECIAL TEST ",
    name: "GROWTH HORMONES (GH) ",
    url: "/",
    price: "800",
  },
  {
    id: 204,
    category: "SPECIAL TEST ",
    name: "ANTI TTG A ",
    url: "/",
    price: "1150",
  },
  {
    id: 205,
    category: "SPECIAL TEST ",
    name: "TPHA ",
    url: "/",
    price: "550",
  },
  {
    id: 206,
    category: "SPECIAL TEST ",
    name: "PHENYTOIN ",
    url: "/",
    price: "850",
  },
  {
    id: 207,
    name: "EPTION ",
    url: "/",
    price: "850",
  },
  {
    id: 208,
    category: "SPECIAL TEST ",
    name: "DILANTIN ",
    url: "/",
    price: "850",
  },
  {
    id: 209,
    category: "SPECIAL TEST ",
    name: "Na VALPROIC ACID ",
    url: "/",
    price: "800",
  },
  {
    id: 210,
    category: "SPECIAL TEST ",
    name: "ANGIOTENSIN CONVERTING ENZYME (ACE) ",
    url: "/",
    price: "1050",
  },
  {
    id: 211,
    category: "SPECIAL TEST ",
    name: "HOMOCYSTINE ",
    url: "/",
    price: "900",
  },
  {
    id: 212,
    category: "SPECIAL TEST ",
    name: "HLA B27 (FCM) ",
    price: "2700",
    url: "/",
  },
  {
    id: 213,
    category: "SPECIAL TEST ",
    name: "D-DIMER ",
    url: "/",
    price: "1100",
  },
  {
    id: 214,
    category: "SPECIAL TEST ",
    name: "17-OH PROGESTERONE ",
    url: "/",
    price: "1300",
  },
  {
    id: 215,
    category: "SPECIAL TEST ",
    name: "TROPONIN-T ",
    url: "/",
    price: "1500",
  },
  {
    id: 216,
    category: "SPECIAL TEST ",
    name: "HLA B27 (PCR) ",
    url: "/",
    price: "3200",
  },
  {
    id: 217,
    category: "SPECIAL TEST ",
    name: "Digital X ray any part- single view ",
    url: "/services/digital-xray",
    price: "450",
  },
  {
    id: 218,
    category: "SPECIAL TEST ",
    name: "Digital X ray any part-two views ",
    url: "/services/digital-xray",
    price: "450",
  },
  {
    id: 219,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "RGU ",
    price: "4000",
  },
  {
    id: 220,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "MCU ",
    price: "6000",
  },
  {
    id: 221,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "HSG including gynae fees (without iv sedation) ",
    price: "4500",
  },
  {
    id: 222,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "IVP ",
    price: "4000",
  },
  {
    id: 223,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "Barium swallow ",
    price: "2500",
  },
  {
    id: 224,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "Barium meal follow through ",
    price: "4000",
  },
  {
    id: 225,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "Barium enema ",
    price: "3500",
  },
  {
    id: 226,
    category: "SPECIAL TEST ",
    url: "/services/digital-xray",
    name: "Loopogram ",
    price: "5000",
  },
 
];
