export const rate = [
  {
    id: 1,
    category: "Service",
    name: "CHEST PA ",
    url: "/",
    price: "450",
  },
  {
    id: 2,
    category: "Service",
    name: "X R LT ARM LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 3,
    category: "Service",
    name: "X-R RT ARM LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 4,
    category: "Service",
    name: "X-R INFANTOGRAM LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 5,
    category: "Service",
    name: "CHEST LAT DECUBITUS ",
    url: "/",
    price: "450",
  },
  {
    id: 6,
    category: "Service",
    name: "X-RAY KUB (14X17) ",
    url: "/",
    price: "450",
  },
  {
    id: 7,
    category: "Service",
    name: "X-R ABDOMEN LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 8,
    category: "Service",
    name: "KUB ",
    url: "/",
    price: "450",
  },
  {
    id: 9,
    category: "Service",
    name: "INVERTOGRAM ",
    url: "/",
    price: "500",
  },
  {
    id: 10,
    category: "Service",
    name: "ABDOMEN ERECT & SUPI ",
    url: "/",
    price: "900",
  },
  {
    id: 11,
    category: "Service",
    name: "ABDOMEN PRONE ",
    url: "/",
    price: "450",
  },
  {
    id: 12,
    category: "Service",
    name: "X R PNS WATER'S ",
    url: "/",
    price: "450",
  },
  {
    id: 13,
    category: "Service",
    name: "XR CERV SPINE AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 14,
    category: "Service",
    name: "X RAY CERVICAL SPINE LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 15,
    category: "Service",
    name: "X-R CERVICAL SPINE AP ",
    url: "/",
    price: "450",
  },
  {
    id: 16,
    category: "Service",
    name: "XR DL.SPINE AP ",
    url: "/",
    price: "450",
  },
  {
    id: 17,
    category: "Service",
    name: "XR DL.SPINE LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 18,
    category: "Service",
    name: "X-RAY D.L.SPINE AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 19,
    category: "Service",
    name: "X-RAY LS SPINEAP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 20,
    category: "Service",
    name: "XR D LUM A/L (14X17) ",
    url: "/",
    price: "900",
  },
  {
    id: 21,
    category: "Service",
    name: "XR LUMBAR SPINE AP ",
    url: "/",
    price: "450",
  },
  {
    id: 22,
    category: "Service",
    name: "XR LUMBAR SPINE LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 23,
    category: "Service",
    name: "XR LUMBAR A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 24,
    category: "Service",
    name: "XR LS SPINE AP ",
    url: "/",
    price: "450",
  },
  {
    id: 25,
    category: "Service",
    name: "XR LS SPINE LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 26,
    category: "Service",
    name: "XR LS SPINE AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 27,
    category: "LOWER LIMBS",
    name: "X R PELVIS AP ",
    url: "/",
    price: "450",
  },

  {
    id: 28,
    category: "LOWER LIMBS",
    name: "X R PELVIS AP ",
    url: "/",
    price: "450",
  },
  {
    id: 29,
    category: "LOWER LIMBS",
    name: "X R SINGLE HIP AP ",
    url: "/",
    price: "450",
  },
  {
    id: 30,
    category: "LOWER LIMBS",
    name: "X R SINGLE HIP LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 31,
    category: "LOWER LIMBS",
    name: "X R SINGLE THIGH AP ",
    url: "/",
    price: "450",
  },
  {
    id: 32,
    category: "LOWER LIMBS",
    name: "X R SINGLE THIGH LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 33,
    category: "LOWER LIMBS",
    name: "X R SINGLE SI JOINT OBL ",
    url: "/",
    price: "450",
  },
  {
    id: 34,
    category: "LOWER LIMBS",
    name: "X R SINGLE KNEE AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 35,
    category: "LOWER LIMBS",
    name: "X R BOTH KNEE AP/L ",
    url: "/",
    price: "1800",
  },
  {
    id: 36,
    category: "LOWER LIMBS",
    name: "X R SINGLE LEG A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 37,
    category: "LOWER LIMBS",
    name: "X R SINGLE ANKLE AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 38,
    category: "LOWER LIMBS",
    name: "X R PATELLA AP ",
    url: "/",
    price: "450",
  },
  {
    id: 39,
    category: "LOWER LIMBS",
    name: "X R SINGLE PATELLA LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 40,
    category: "LOWER LIMBS",
    name: "X R BOTH HIP AP ",
    url: "/",
    price: "900",
  },
  {
    id: 41,
    category: "LOWER LIMBS",
    name: "X R BOTH HEEL LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 42,
    category: "LOWER LIMBS",
    name: "X R FEMUR AP ",
    url: "/",
    price: "450",
  },
  {
    id: 43,
    category: "LOWER LIMBS",
    name: "XR THUMB AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 44,
    category: "LOWER LIMBS",
    name: "X-R FOOT AP/OBL ",
    url: "/",
    price: "900",
  },
  {
    id: 45,
    category: "LOWER LIMBS",
    name: "X R HEEL AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 46,
    category: "LOWER LIMBS",
    name: "X-R CALCANEUM AP ",
    url: "/",
    price: "450",
  },
  {
    id: 47,
    category: "LOWER LIMBS",
    name: "X-R LEFT KNEE SKYLIN ",
    url: "/",
    price: "450",
  },
  {
    id: 48,
    category: "LOWER LIMBS",
    name: "XR B/L CALCANEUM LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 49,
    category: "LOWER LIMBS",
    name: "X R BOTH FOOT A/L ",
    url: "/",
    price: "1800",
  },
  {
    id: 50,
    category: "LOWER LIMBS",
    name: "X-R B/L CALC AXL ",
    url: "/",
    price: "1800",
  },
  {
    id: 51,
    category: "LOWER LIMBS",
    name: "X R BOTH ANKLE A/L ",
    url: "/",
    price: "1800",
  },
  {
    id: 52,
    category: "LOWER LIMBS",
    name: "X R BOTH FEET A/L ",
    url: "/",
    price: "1800",
  },
  {
    id: 53,
    category: "LOWER LIMBS",
    name: "X R BOTH HEEL AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 54,
    category: "LOWER LIMBS",
    name: "XR BOTH FEMUR AP ",
    url: "/",
    price: "900",
  },
  {
    id: 55,
    category: "LOWER LIMBS",
    name: "X R BOTH LEG AP ",
    url: "/",
    price: "900",
  },
  {
    id: 56,
    category: "LOWER LIMBS",
    name: "X-RAY RT LEG LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 57,
    category: "LOWER LIMBS",
    name: "X-R BOTH ANKLE AP ",
    url: "/",
    price: "900",
  },
  {
    id: 58,
    category: "LOWER LIMBS",
    name: "BOTH KNEE AP STANDIN ",
    url: "/",
    price: "900",
  },
  {
    id: 59,
    category: "LOWER LIMBS",
    name: "X R BOTH HIPS LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 60,
    category: "LOWER LIMBS",
    name: "X-RAY PELVIS AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 61,
    category: "LOWER LIMBS",
    name: "X-R B ANK STRESS AP/L ",
    url: "/",
    price: "900",
  },
  {
    id: 62,
    category: "LOWER LIMBS",
    name: "X R BOTH FEET LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 63,
    category: "LOWER LIMBS",
    name: "BOTH PATELLA SKYLINE ",
    url: "/",
    price: "900",
  },
  {
    id: 64,
    category: "UPPER LIMBS",
    name: "X R LEFT SH AP ",
    url: "/",
    price: "450",
  },
  {
    id: 65,
    category: "UPPER LIMBS",
    name: "X R SH AP/L L ",
    url: "/",
    price: "900",
  },
  {
    id: 66,
    category: "UPPER LIMBS",
    name: "X R LEFT CLAVICLE ",
    url: "/",
    price: "450",
  },
  {
    id: 67,
    category: "UPPER LIMBS",
    name: "L ARM AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 68,
    category: "UPPER LIMBS",
    name: "XR LEFT ELBOW A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 69,
    category: "UPPER LIMBS",
    name: "X R FOREARM A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 70,
    category: "UPPER LIMBS",
    name: "X R LT WRIST A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 71,
    category: "UPPER LIMBS",
    name: "X R LT HAND A ",
    url: "/",
    price: "900",
  },
  {
    id: 72,
    category: "UPPER LIMBS",
    name: "X R SCAPULA A ",
    url: "/",
    price: "450",
  },
  {
    id: 73,
    category: "UPPER LIMBS",
    name: "X R SCAP A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 74,
    category: "UPPER LIMBS",
    name: "X R LT HAND A/OB ",
    url: "/",
    price: "900",
  },
  {
    id: 75,
    category: "UPPER LIMBS",
    name: "X R LT TH A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 76,
    category: "UPPER LIMBS",
    name: "X R LT IND FING A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 77,
    category: "UPPER LIMBS",
    name: "X R LT MID FIN A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 78,
    category: "UPPER LIMBS",
    name: "X R LT RING FIN A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 79,
    category: "UPPER LIMBS",
    name: "X R LT LAT FING A/L ",
    url: "/",
    price: "900",
  },
  {
    id: 80,
    category: "UPPER LIMBS",
    name: "X R LT ELBOW AP ",
    url: "/",
    price: "450",
  },
  {
    id: 81,
    category: "UPPER LIMBS",
    name: "X R LT ELB LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 82,
    category: "UPPER LIMBS",
    name: "X R LT ARM LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 83,
    category: "UPPER LIMBS",
    name: "X R LT SHOULD LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 84,
    category: "UPPER LIMBS",
    name: "X-R LT WRIST OBL",
    url: "/",
    price: "450",
  },
  {
    id: 85,
    category: "UPPER LIMBS",
    name: "X-R LT HAND AP ",
    url: "/",
    price: "450",
  },
  {
    id: 86,
    category: "UPPER LIMBS",
    name: "BOTH HANDS AP& OBLIQ ",
    url: "/",
    price: "900",
  },
  {
    id: 87,
    category: "UPPER LIMBS",
    name: "X R BOTH HA AP ",
    url: "/",
    price: "900",
  },
  {
    id: 88,
    category: "UPPER LIMBS",
    name: "BOTH WR AP ",
    url: "/",
    price: "900",
  },
  {
    id: 89,
    category: "UPPER LIMBS",
    name: "BOTH ELBOWS AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 90,
    category: "UPPER LIMBS",
    name: "X R BOTH ELBOW AP ",
    url: "/",
    price: "900",
  },
  {
    id: 91,
    category: "UPPER LIMBS",
    name: "X R BOTH ELBOW LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 92,
    category: "UPPER LIMBS",
    name: "X-R BOTH ARM AP ",
    url: "/",
    price: "900",
  },
  {
    id: 93,
    category: "UPPER LIMBS",
    name: "X BOTH SHOULD AP/LAT ",
    url: "/",
    price: "1800",
  },
  {
    id: 94,
    category: "UPPER LIMBS",
    name: "X BOTH WRIST AP/LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 95,
    category: "UPPER LIMBS",
    name: "X-R BOTH HAND LAT ",
    url: "/",
    price: "900",
  },
  {
    id: 96,
    category: "UPPER LIMBS",
    name: "X-R BOTH SHOULD AP ",
    url: "/",
    price: "900",
  },
  {
    id: 97,
    category: "OTHERS",
    name: "S.TISSUE NECK LAT ",
    url: "/",
    price: "450",
  },
  {
    id: 98,
    category: "OTHERS",
    name: "SOFT TISSUES  ADENOI ",
    url: "/",
    price: "450",
  },

  {
    id: 99,
    category: "SPECIAL PROCEDURES",
    name: "BA MEAL ",
    url: "/",
    price: "5000",
},
{
    id: 100,
    category: "SPECIAL PROCEDURES",
    name: "BARIUM ENEMA ",
    url: "/",
    price: "4000",
},
{
    id: 101,
    category: "SPECIAL PROCEDURES",
    name: "BARIM MEAL UPPER GIT ",
    url: "/",
    price: "3000",
},
{
    id: 102,
    category: "SPECIAL PROCEDURES",
    name: "BARIUM SWALLOW ",
    url: "/",
    price: "2700",
},
{
    id: 103,
    category: "SPECIAL PROCEDURES",
    name: "IVP ",
    url: "/",
    price: "4000",
},
{
    id: 104,
    category: "SPECIAL PROCEDURES",
    name: "HSG ",
    url: "/",
    price: "4500",
}];
